# Generated by Django 5.2.1 on 2025-05-26 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_decoration', models.CharField(max_length=120, verbose_name='Название украшения')),
                ('decoration', models.ImageField(upload_to='decoration/%Y/%m/%d', verbose_name='Изображение украшения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за украшение')),
            ],
            options={
                'verbose_name': 'Украшение',
                'verbose_name_plural': 'Украшения',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flower', models.CharField(max_length=120, verbose_name='Название цветка')),
                ('image_flower', models.ImageField(upload_to='flowers/%Y/%m/%d', verbose_name='Изображение цветка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за один цветок')),
                ('counts', models.IntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pack', models.CharField(max_length=120, verbose_name='Название обертки')),
                ('pack', models.ImageField(upload_to='pack/%Y/%m/%d', verbose_name='Изображение обертки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за обертку')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_name', models.CharField(max_length=120, verbose_name='Рубрика статьи')),
            ],
            options={
                'verbose_name': 'Рубрика статьи',
                'verbose_name_plural': 'Рубрики статей',
            },
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flowers', models.JSONField()),
                ('name_pack', models.CharField(blank=True, max_length=255, null=True)),
                ('name_decoration', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Букет клиента',
                'verbose_name_plural': 'Букеты клиентов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, upload_to='answer/%Y/%m/%d', verbose_name='Изображение цветка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('decorated', 'Оформлен'), ('delivery', 'В пути'), ('delivered', 'Доставлен')], default='decorated', max_length=50, verbose_name='Статус доставки')),
                ('sender_name', models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя отправителя')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона отправителя')),
                ('recipient_name', models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона получателя')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=50, verbose_name='Тип доставки')),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('pay_type', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой при получении'), ('online', 'Оплатить онлайн')], max_length=50, verbose_name='Тип оплаты')),
                ('card_number', models.CharField(blank=True, max_length=255)),
                ('CVV', models.CharField(blank=True, max_length=255)),
                ('bouquets', models.JSONField(blank=True, null=True, verbose_name='Букеты')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('counts', models.IntegerField(default=1, verbose_name='Количество товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Оценка')),
                ('is_active', models.CharField(choices=[('published', 'Опубликован'), ('cancelled', 'Отменен')], max_length=50, verbose_name='Статус отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок статьи')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d', verbose_name='Изображение статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.rubric', verbose_name='Выберите рубрику статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBouquetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('decorated', 'Оформлен'), ('delivery', 'В пути'), ('delivered', 'Доставлен')], default='decorated', max_length=50, verbose_name='Статус доставки')),
                ('name_pack', models.CharField(blank=True, max_length=255, null=True)),
                ('name_decoration', models.CharField(blank=True, max_length=500, null=True)),
                ('flowers', models.JSONField(blank=True, null=True)),
                ('sender_name', models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя отправителя')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона отправителя')),
                ('recipient_name', models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона получателя')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=50, verbose_name='Тип доставки')),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('pay_type', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой при получении'), ('online', 'Оплатить онлайн')], max_length=50, verbose_name='Тип оплаты')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты')),
                ('CVV', models.CharField(blank=True, max_length=20, null=True, verbose_name='Защитный код с обратной стороны')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bouquet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ клиентского букета',
                'verbose_name_plural': 'Заказы клиентских букетов',
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mainapp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк статьи',
                'verbose_name_plural': 'Лайки статей',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_basket_item')],
            },
        ),
    ]
